import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>project-next-trainy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={styles.grid}>
          <img />
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Hello everyone!</h1>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        {data.map((ev) => (
          <a key={ev.id} href={`/events/${ev.id}`}>
          <Image alt={ev.title} src={ev.image} width={200} height={250} />
          <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>
        ))}
        {/* <a href='events/london'>
          <img/>
          <h2>Events in Netherlands</h2>
          <p>
            Keukenhof is known as the "Garden of Europe" and is one
            of the largest flower gardens in the world. The garden
            covers an area of over 79 acres and is home to over 7 million
            tulips, daffodils, and hyacinths, among other flowers. Keukenhof
            is only open for a few months every year, from late March to mid-May,
            when the flowers are in bloom.
          </p>
        </a>

        <a href='events/san-francisco'>
          <img/>
          <h2>Events in Sangerhausen</h2>
          <p>
            One of the most famous is the Europa-Rosarium in Sangerhausen.
            The Europa-Rosarium is located in the town of Sangerhausen, in
            the state of Saxony-Anhalt, and is one of the largest rose gardens
            in the world. The garden was established in 1903 and has been
            continuously expanded and improved over the years.
          </p>
        </a>
        
        <a href='events/barcelona'>
          <img/>
          <h2>Events in England</h2>
          <p>
            The David Austin Rose Garden is a famous rose garden located in
            Albrighton, England, which is about 140 miles northwest of London.
            The David Austin Rose Garden is a must-visit destination for anyone
            who loves roses and gardening. It is not only a beautiful display of
            some of the world's most stunning roses, but it is also a tribute to
            the legacy of David Austin, who dedicated his life to creating beautiful
            and fragrant roses that bring joy to people's lives.
          </p>
        </a> */}

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className={styles.center}>
        <p>2023 Time to code - Project-next-trainy</p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories} = await import('../data/data.json')
  console.log(events_categories);
  //const res = await fetch('URL');
  //const data =await res.json()
    return {
        props: {
           data: events_categories,
        },
    }
}
