import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>project-next-trainy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={styles.grid}>
          <img />
          <Link href='/' passHref legacyBehavior><a>Home</a></Link>
          <Link href='/events' passHref legacyBehavior><a>Events</a></Link>
          <Link href='/about-us' passHref legacyBehavior><a>About Us</a></Link>
        </nav>
      </header>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Hello everyone!</h1>          
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} passHref legacyBehavior>
          <a>
          <Image alt={ev.title} src={ev.image} width={200} height={250} />
          <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a></Link>
        ))}       

        <div className={styles.grid}>        
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className={styles.center}>
        <p>2023 Time to code - Project-next-trainy</p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories} = await import('../data/data.json')
  console.log(events_categories);
  //const res = await fetch('URL');
  //const data =await res.json()
    return {
        props: {
           data: events_categories,
        },
    }
}
