import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { HomePage } from '../src/components/home/home-page';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>project-next-trainy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <HomePage data={data} />      
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories} = await import('../data/data.json')
  console.log(events_categories);
  //const res = await fetch('URL');
  //const data =await res.json()
    return {
        props: {
           data: events_categories,
        },
    }
}
